config/routes.rb
Rails.application.routes.draw do
  root to: 'pages#home'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  # get 'products', to: 'products#index'
  # get 'products/:id', to: 'products#show'
  resources :points, only: [:index]
  resources :collections, only: [:show, :index, :update]
  resources :products, only: [:show, :index]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/collection.rb
class Collection < ApplicationRecord
  has_many_attached :photos
end

app/models/point.rb
class Point < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/collections_controller.rb
class CollectionsController < ApplicationController
  def index
   @collections = Collection.all
  #  @collections = ShopifyAPI::CustomCollection.all
  end
   def show
    @collections = Collection.all
    @chosen_collection = Collection.find(params[:id])
    @collection = ShopifyAPI::CustomCollection.find(:all, :params => {:title => "#{@chosen_collection.name}"}).first
    @products = ShopifyAPI::Product.find(:all, :params => {:collection_id => @collection.id})
   # products = RestClient.get("https://#{ENV['SHOPIFY_API_KEY']}:#{ENV['SHOPIFY_PASSWORD']}@dryandmyrtille.myshopify.com/admin/api/2020-01/products.json")
   # render json: products
  end
  def update
    @collection = Collection.find(params[:id])
    @collection.update(collection_params)
  end
  def collection_params
  params.require(:collection).permit(:name, photos: [])
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home

  end
  def product
    shop = ShopifyAPI::Shop.current
    @name = shop.name
    @products = ShopifyAPI::Product.all
  end
end

app/controllers/points_controller.rb
class PointsController < ApplicationController

  def index
    @points = Point.all

    @markers = @points.map do |point|
      {
        lat: point.latitude,
        lng: point.longitude
      }
    end
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  def index
    shop = ShopifyAPI::Shop.current
    @name = shop.name
    @products = ShopifyAPI::Product.all
  end
  def show
    @product = ShopifyAPI::Product.find(params[:id])
    @same_collection = ShopifyAPI::CustomCollection.find(:all, :params => {:title => "#{@product.collections.first.title}"}).first
    @products_collection = ShopifyAPI::Product.find(:all, :params => {:collection_id => @same_collection.id})
    @type_collection = ShopifyAPI::SmartCollection.find(:all, :params => {:handle => "#{@product.product_type}s"})
    unless @type_collection.empty?
      @products_type = ShopifyAPI::Product.find(:all, :params => {:collection_id => @type_collection.first.id})
    else
      @products_type = ShopifyAPI::Product.all.sample(5)
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/collections/index.html.erb
<%= render '/shared/menu_collections' %>

<div class="masonery_container">
  <%#  i = 1 %>
  <% @collections.each do |collection| %>

  <div class="card py-3">
    <%#= i %>
    <%= link_to collection_path(collection), class:"d-flex flex-column justify-content-around", style: "height:100%;" do %>
    <%# i += 1 %>
    <div class="card_title">
      <h4><%= collection.name %></h4>
    </div>
    <div class="card_sous-title">
      <h5><%= collection.theme %></h5>
    </div>
    <div class="card_text px-5">
      <p><%= collection.description %></p>
    </div>
    <% end %>
  </div>
  <% collection.photos.each do |photo| %>
  <div class="photo_masonery">
    <%= cl_image_tag photo.key %>
    <%#= i %>
  </div>
  <%# i += 1 %>
  <% end %>

  <% end %>
</div>

app/views/collections/show.html.erb
<%= render '/shared/menu_collections' %>

<%#= @collection.title %>
<%#= simple_form_for(@chosen_collection) do |f| %>
<%#= f.input :photos, as: :file, input_html: { multiple: true } %>
<%#= f.submit %>
<%# end %>


<div class="row">
  <div class="col-md-6 col-12">
    <%= image_tag @collection.image.src, style:"width: 50vw; object-fit: contain;" %>
  </div>
  <div class="col-md-6 col-12 d-flex flex-column align-items-center">
    <p id="desc"><%= @chosen_collection.description %></p>

    <% @products.each do |product| %>
      <%= link_to product_path(product.id) do %>
      <div class="card_product d-flex mx-auto m-2 p-1 bg-light">
        <div class="card_img">
          <%= image_tag product.image.src %>
        </div>
        <div class="card_text d-flex flex-column justify-content-around align-items-center">
          <h5><%= product.title %></h5>
          <p><%= product.variants.first.sku %></p>
          <p><strong><%= product.variants.first.price %> €</strong></p>
        </div>
      </div>
      <% end %>
    <% end %>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>Dryandmyrtille</title>
    <%= csrf_meta_tags %>
    <%= action_cable_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%#= stylesheet_pack_tag 'application', media: 'all' %> <!-- Uncomment if you import CSS in app/javascript/packs/application.js -->
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload', defer: true %>
  </head>
  <body>
    <%= render '/shared/navbar' %>
    <%= yield %>
    <%= render '/shared/footer' %>
    <%= javascript_include_tag 'application' %>
  </body>
</html>

app/views/pages/home.html.erb
<div class="banner">
  <div class="banner_container">
    <%= link_to collections_path do %>
      <button class="btn btn-ghost">Découvrir</button>
    <% end %>
  </div>
</div>


<%= link_to 'produits', products_path %>
<%= link_to 'collections', collections_path %>
<%= link_to 'points', points_path %>

app/views/pages/product.html.erb
<%= @name %>

<ul>
<% @products.each do |product| %>
<li>
  <%= product.title %>
  <%= image_tag product.image.src, style:"width: 120px; height: 120px object-fit: contain;"%>
  </li>
  <% end %>
  </ul>

app/views/points/index.html.erb
<ul>
<% @points.each do |point| %>
<li>
  <%= point.name %>
 </li>
  <% end %>
  </ul>
<div id="map"
    style="width: 100%;
    height: 600px;"
    data-markers="<%= @markers.to_json %>"
    data-mapbox-api-key="<%= ENV['MAPBOX_API_KEY'] %>"></div>

app/views/products/index.html.erb
<%= @name %>

<ul>
<% @products.each do |product| %>
<li>
  <%= product.title %>
  <%= image_tag product.image.src, style:"width: 120px; height: 120px object-fit: contain;"%>
  </li>
  <% end %>
  </ul>

app/views/products/show.html.erb
    <div class="row">
      <div class="col">
        <div class="card_img_product">
          <%= image_tag @product.image.src %>
        </div>
      </div>
      <div class="col">
        <h5><%= @product.title %></h5>
        <p><%= @product.variants.first.sku %></p>
        <p><strong><%= @product.variants.first.price %> €</strong></p>
      </div>
      <div class="col">
        <div class="buttons_buy">

        </div>
      </div>
    </div>


<h6>Dans la même collection ...</h6>
<div class="products_collection_mini_card d-flex">
    <% @products_collection.each do |product| %>
      <%= link_to product_path(product.id) do %>
      <div class="mini_card_product m-2 bg-light">
        <div class="mini_card_img">
          <%= image_tag product.image.src %>
        </div>
      </div>
      <% end %>
    <% end %>
</div>
<h6>Vous pourriez également aimer</h6>
<div class="products_type_mini_card d-flex">
    <% @products_type.each do |product| %>
      <%= link_to product_path(product.id) do %>
      <div class="mini_card_product m-2 bg-light">
        <div class="mini_card_img">
          <%= image_tag product.image.src %>
        </div>
      </div>
      <% end %>
    <% end %>
</div>

app/views/shared/_burger.html.erb
<div class="menu-wrap">
    <input type="checkbox" class="toggler">
    <div class="hamburger"><div class="in"></div></div>
    <div class="menu">
      <div>
        <div>
          <ul>
            <li><%= link_to 'Accueil', root_path %></li>
            <li><a href="#">A propos</a></li>
            <li><%= link_to 'Collection', collections_path %></li>
            <li><a href="#">Sur mesure</a></li>
            <li><a href="#">En savoir plus</a></li>
            <li><%= link_to 'Points de vente', points_path %></li>
            <li>_________________</li>
            <li><a href="#">Contactez-nous</a></li>
          </ul>
        </div>
      </div>
    </div>
  </div>

app/views/shared/_footer.html.erb
<div class="adv">
  <div class="row m-3">
    <div class="col m-3">
      <h5>Des produits naturels et écoresponsables</h5>
    </div>
    <div class="col m-3">
      <h5>made in france, made in provence, faits avec amour</h5>
    </div>
    <div class="col m-3">
      <h5>Des créations uniques, des envois soignés</h5>
    </div>
  </div>
</div>
<div class="footer">
  <div class="footer-links">
    <a href="#"><i class="fab fa-github"></i></a>
    <a href="#"><i class="fab fa-instagram"></i></a>
    <a href="#"><i class="fab fa-facebook"></i></a>
    <a href="#"><i class="fab fa-twitter"></i></a>
    <a href="#"><i class="fab fa-linkedin"></i></a>
  </div>
  <div class="footer-copyright">
    réalisé par glumy.tech
  </div>
</div>

app/views/shared/_menu_collections.html.erb
<div id="menu_collections_navbar">
<%= link_to collections_path do %>
  <h1>Collections</h1>
<% end %>
<ul class="nav justify-content-around">
  <% @collections.each do |collection| %>
    <li class="nav-item">
    <% active = "active" if request.path == collection_path(collection) %>
      <%= link_to "#{collection.name}", collection_path(collection), class: "nav-link #{active}" %>
    </li>
  <% end %>
</ul>


</div>

app/views/shared/_navbar.html.erb
<%= render 'shared/burger' %>
  <header class="showcase">
    <div class="showcase-inner navbar-lewagon">
    <div class="navbar-brand"> </div>
    <div class="logo_minimal">
    <%= link_to root_path do %>
      <% unless request.path == root_path %>
        <div class="logo-text">Dry & Myrtille</div>
        <p>Accessoires fleuris</p>
        <% end %>
    <% end %>
    </div>
    <%= link_to collections_path do %>
      <button class="btn btn-ghost">Contact</button>
    <% end %>
    </div>
  </header>